todo/urls.py
from django.urls import path

from todo.views import TaskListView, TagListView, TaskCreateView, TaskUpdateView, TaskDeleteView, TagCreateView, \
    TagUpdateView, TagDeleteView, TaskChangeStatusView

urlpatterns = [
    path("", TaskListView.as_view(), name="task-list"),
    path("tasks/create/", TaskCreateView.as_view(), name="task-create"),
    path("tasks/<int:pk>/update/", TaskUpdateView.as_view(), name="task-update"),
    path("tasks/<int:pk>/delete/", TaskDeleteView.as_view(), name="task-delete"),
    path("tasks/<int:pk>/change_status/", TaskChangeStatusView.as_view(), name="change-status"),
    path("tags/", TagListView.as_view(), name="tag-list"),
    path("tags/create/", TagCreateView.as_view(), name="tag-create"),
    path("tags/<int:pk>/update/", TagUpdateView.as_view(), name="tag-update"),
    path("tags/<int:pk>/delete/", TagDeleteView.as_view(), name="tag-delete"),
]

app_name = "todo"

todo_list/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("todo.urls", namespace="todo"))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

todo/models.py
from django.db import models


class Tag(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Task(models.Model):
    content = models.TextField()
    created_at = models.DateTimeField(null=True)
    deadline = models.DateTimeField(null=True, blank=True)
    is_completed = models.BooleanField(null=True)
    tags = models.ManyToManyField(Tag, related_name="tasks")

    class Meta:
        ordering = ["is_completed", "created_at"]

todo/views.py
from django.urls import reverse_lazy
from django.views import generic, View
from django.shortcuts import get_object_or_404, redirect

from todo.models import Task, Tag


class TaskListView(generic.ListView):
    model = Task


class TaskCreateView(generic.CreateView):
    model = Task
    fields = "__all__"
    success_url = reverse_lazy("todo:task-list")


class TaskUpdateView(generic.UpdateView):
    model = Task
    fields = "__all__"
    success_url = reverse_lazy("todo:task-list")


class TaskChangeStatusView(View):
    @staticmethod
    def post(request, pk):
        task = get_object_or_404(Task, pk=pk)
        task.is_completed = not task.is_completed
        task.save()
        return redirect("todo:task-list")


class TaskDeleteView(generic.DeleteView):
    model = Task
    success_url = reverse_lazy("todo:task-list")


class TagListView(generic.ListView):
    model = Tag


class TagCreateView(generic.CreateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("todo:tag-list")


class TagUpdateView(generic.UpdateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("todo:tag-list")


class TagDeleteView(generic.DeleteView):
    model = Task
    success_url = reverse_lazy("todo:tag-list")

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% block title %}<title>TODO</title>{% endblock %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
          integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2"
          crossorigin="anonymous">
    <!-- Add additional CSS in static file -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body>
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-2">

            {% block sidebar %}
                {% include "includes/sidebar.html" %}
            {% endblock %}

        </div>
        <div class="col-sm-10 ">

            {% block content %}{% endblock %}

        </div>
    </div>
</div>
</body>

</html>

templates/includes/sidebar.html
<ul class="sidebar-nav list-group">
  <li class="list-group-item"><a href="{% url 'todo:task-list' %}">Home</a></li>
  <li class="list-group-item"><a href="{% url 'todo:tag-list' %}">Tags</a></li>
</ul>

templates/todo/tag_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete tag?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
  </form>
{% endblock %}

templates/todo/tag_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} tag</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/todo/tag_list.html
{% extends "base.html" %}

{% block content %}
  <h1>
    Tags
    <a class="btn btn-primary float-right" href="{% url 'todo:tag-create' %}">Add</a>
  </h1>
  {% if tag_list %}
    <table class="table table-bordered">
      <tr style="background-color: lightgray">
        <th class="text-center">Name</th>
        <th class="text-center">Update</th>
        <th class="text-center">Delete</th>
      </tr>
      {% for tag in tag_list  %}
      <tr>
        <td class="text-center">{{ tag.name }}</td>
        <td><a class="btn btn-secondary btn-block" href="{% url 'todo:tag-update' pk=tag.id %}">Update</a></td>
        <td><a class="btn btn-secondary btn-block" href="{% url 'todo:tag-delete' pk=tag.id  %}">Delete</a></td>
      </tr>
      {% endfor %}
    </table>

  {% else %}
    <p>There are no tags</p>
{% endif %}
{% endblock %}

templates/todo/task_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete task?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
  </form>
{% endblock %}

templates/todo/task_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} task</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/todo/task_list.html
{% extends "base.html" %}

{% block content %}
  <h1>
    TODO List
    <a href="{% url 'todo:task-create' %}" class="btn btn-primary link-to-page float-right">Add task</a>
  </h1>

  {% if task_list %}
    <ul class="list-inline">
      {% for task in task_list  %}
        <li>
          <form method="post" action="{% url 'todo:change-status' pk=task.pk %}" style="display: inline;">
            {% csrf_token %}
            {% if task.is_completed %}
              <button type="submit" class="btn btn-secondary link-to-page float-right">Undo</button>
            {% else %}
              <button type="submit" class="btn btn-success link-to-page float-right">Complete</button>
            {% endif %}
          </form>
          <p>
            <strong>
              {{ task.content }}
              {% if task.is_completed == True %} <span class="text-success">Done</span>
              {% else %} <span class="text-danger">Not done</span>
              {% endif %}
            </strong>
          </p>
          <p>
            Created: {{ task.created_at }}
            {% if task.deadline %} <span class="text-warning">Deadline: {{ task.deadline }}</span>
            {% endif %}
          </p>
          <p>
            Tags: {% for tag in task.tags.all %} {{ tag.name }} {% endfor %}
            <a href="{% url 'todo:task-update' pk=task.pk %}">Update</a>
            <a href="{% url 'todo:task-delete' pk=task.pk %}">Delete</a>
          </p>
        </li>
        <hr>
      {% endfor %}
    </ul>
  {% else %}
    <p>There are no tasks</p>
  {% endif %}
{% endblock %}